global using AutoMapper;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.Rendering;
global using Microsoft.EntityFrameworkCore;
global using System.Diagnostics;
global using WebApp.DataAccess.Data;
global using WebApp.DataAccess.UnitOfWork;
global using WebApp.Models;
global using WebApp.Models.ViewModels;
